version: 2.0

defaults: &defaults
  working_directory: ~/sam-webpack-plugin
  docker:
    - image: circleci/node:chakracore-10.13.0

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v-deps-{{ .Branch }}-
            - v-deps-
      - run: npm install
      - save_cache:
          key: v-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/sam-webpack-plugin
      - run: npm run lint
      - run: npm run test

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/sam-webpack-plugin
      - run: npm run build.prod

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/sam-webpack-plugin
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  install-test-build:
    jobs:
      - install:
          filters:
            branches:
              only: master
      - test:
          requires:
            - install
          filters:
            branches:
              only: master
      - build:
          requires:
            - install
            - test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - install
            - test
            - build
          filters:
            branches:
              only: master
