version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

defaults: &defaults
  working_directory: ~/sam-webpack-plugin
  docker:
    - image: circleci/node:9.11.1

releaseFilters: &releaseFilters
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

masterFilters: &masterFilters
  filters:
    branches:
      only:
        - master
        - dev

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v-deps-{{ .Branch }}-
            - v-deps-
      - run: npm install
      - save_cache:
          key: v-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/
          paths:
            - sam-webpack-plugin

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint
      - run: npm run test
      - codecov/upload:
          file: ~/sam-webpack-plugin/coverage

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run build.prod

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_TOKEN" > ~/sam-webpack-plugin/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  install-test-build:
    jobs:
      - install:
          <<: *masterFilters
      - test:
          <<: *masterFilters
          requires:
            - install
      - build:
          <<: *masterFilters
          requires:
            - test

  release-deploy:
    jobs:
      - install:
          <<: *releaseFilters
      - test:
          <<: *releaseFilters
          requires:
            - install
      - build:
          <<: *releaseFilters
          requires:
            - test
      - publish:
          <<: *releaseFilters
          requires:
            - build
